### ISSUE TITLE
[Bug]: CANNOT OPEN CONFIG. 

### ISSUE THREAD

**Issue by CREEPER900** [Fuzss/easymagic#63]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

LATEST

### Other Mods Involved (Required)

No

### Notes (Required)

I CANNOT OPEN CONFIG TAB IN MODS MENU. IT SIMPLY COULD NOT WORK DESPITE CLICKING. I can see the mod in mods menu but I clicked it i, it did not show up anything. 

### latest.log (Required)

[20:26:57] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11 [20:26:57] [main/INFO]: Loading 60 mods: 	- configured 2.5.0 	- easymagic 21.0.1 	- fabric-api 0.100.4+1.21 	   |-- fabric-api-base 0.4.42+6573ed8cd1 	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1 	   |-- fabric-biome-api-v1 13.0.28+6fc22b99d1 	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1 	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1 	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1 	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1 	   |-- fabric-command-api-v1 1.2.48+f71b366fd1 	   |-- fabric-command-api-v2 2.2.27+6a6dfa19d1 	   |-- fabric-commands-v0 0.2.65+df3654b3d1 	   |-- fabric-content-registries-v0 8.0.14+b5597344d1 	   |-- fabric-convention-tags-v1 2.0.15+7f945d5bd1 	   |-- fabric-convention-tags-v2 2.3.2+78017270d1 	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1 	   |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1 	   |-- fabric-data-generation-api-v1 20.2.9+16c4ae25d1 	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1 	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1 	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1 	   |-- fabric-game-rule-api-v1 1.0.52+6573ed8cd1 	   |-- fabric-item-api-v1 11.0.0+afdfc921d1 	   |-- fabric-item-group-api-v1 4.1.2+78017270d1 	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1 	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1 	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1 	   |-- fabric-loot-api-v2 3.0.11+6573ed8cd1 	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1 	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1 	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1 	   |-- fabric-object-builder-api-v1 15.1.12+d1321076d1 	   |-- fabric-particles-v1 4.0.2+6573ed8cd1 	   |-- fabric-recipe-api-v1 5.0.10+65089712d1 	   |-- fabric-registry-sync-v0 5.0.23+78017270d1 	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1 	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1 	   |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1 	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1 	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1 	   |-- fabric-rendering-v0 1.1.70+df3654b3d1 	   |-- fabric-rendering-v1 5.0.4+5a8c785ed1 	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1 	   |-- fabric-resource-loader-v0 1.1.5+78017270d1 	   |-- fabric-screen-api-v1 2.0.24+b5597344d1 	   |-- fabric-screen-handler-api-v1 1.3.80+b5597344d1 	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1 	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1 	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1 	- fabricloader 0.15.11 	   \-- mixinextras 0.3.5 	- forgeconfigapiport 21.0.1 	   |-- com_electronwill_night-config_core 3.7.4 	   \-- com_electronwill_night-config_toml 3.7.4 	- java 21 	- minecraft 1.21 	- modmenu 11.0.1 	   \-- placeholder-api 2.4.0-pre.2+1.21 	- puzzleslib 21.0.8 [20:26:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/sehna/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT [20:26:57] [main/INFO]: Compatibility level set to JAVA_21 [20:26:57] [main/WARN]: Reference map 'forgeconfigapiport.common.refmap.json' for forgeconfigapiport.common.mixins.json could not be read. If this is a development environment you can ignore this message [20:26:59] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5). [20:27:00] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 441 milliseconds [20:27:06] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD] [20:27:06] [Render thread/INFO]: Setting user: vvghfhgf [20:27:06] [Render thread/INFO]: Constructing common components for easymagic:main [20:27:07] [Render thread/INFO]: Loading client config for easymagic [20:27:07] [Render thread/INFO]: Constructing common components for puzzleslib:main [20:27:07] [Render thread/INFO]: Successfully loaded config provider: com.mrcrayfish.configured.impl.framework.FrameworkConfigProvider [20:27:07] [Render thread/INFO]: Successfully loaded config provider: com.mrcrayfish.configured.impl.jei.JeiConfigProvider [20:27:07] [Render thread/INFO]: Constructing client components for easymagic:main [20:27:07] [Render thread/INFO]: [Indigo] Registering Indigo renderer! [20:27:07] [Render thread/INFO]: Checking mod updates... [20:27:07] [Render thread/INFO]: Constructing client components for puzzleslib:main [20:27:08] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot [20:27:08] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.100.4+1.21', (-> 0.100.6+1.21) [20:27:11] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, configured, easymagic, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, modmenu [20:27:11] [Worker-Main-5/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading [20:27:11] [Worker-Main-1/INFO]: Found unifont_jp_patch-15.1.05.hex, loading [20:27:12] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play [20:27:12] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break [20:27:13] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Hoparlör (Realtek(R) Audio) [20:27:13] [Render thread/INFO]: Sound engine started [20:27:13] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas [20:27:13] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas [20:27:13] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas [20:27:13] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas [20:27:13] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas [20:27:13] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas [20:27:13] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas [20:27:13] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas [20:27:13] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas [20:27:13] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas [20:27:13] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas [20:27:13] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas [20:27:13] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas [20:27:13] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas [20:27:13] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program. [20:27:14] [IO-Worker-1/INFO]: Could not authorize you against Realms server: Invalid session id [20:27:14] [IO-Worker-1/ERROR]: Couldn't connect to realms net.minecraft.class_4355: Realms authentication error with message 'Invalid session id' 	at net.minecraft.class_4341.method_20998(class_4341.java:447) ~[client-intermediary.jar:?] 	at net.minecraft.class_4341.method_21027(class_4341.java:232) ~[client-intermediary.jar:?] 	at net.minecraft.class_8647.method_52627(class_8647.java:51) ~[client-intermediary.jar:?] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] [20:27:18] [Render thread/WARN]: Warning! Mod com_electronwill_night-config_core has a broken icon, loading default icon [20:27:32] [Render thread/INFO]: Loaded 1290 recipes [20:27:32] [Render thread/INFO]: Loaded 1399 advancements [20:27:32] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 2.030 ms [20:27:32] [Server thread/INFO]: Loading server config for easymagic [20:27:32] [Server thread/INFO]: Starting integrated minecraft server version 1.21 [20:27:32] [Server thread/INFO]: Generating keypair [20:27:33] [pool-5-thread-1/INFO]: Reloading server config for easymagic [20:27:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld [20:27:33] [Render thread/INFO]: Preparing spawn area: 0% [20:27:33] [Render thread/INFO]: Time elapsed: 433 ms [20:27:34] [Server thread/INFO]: Changing view distance to 12, from 10 [20:27:34] [Server thread/INFO]: Changing simulation distance to 12, from 0 [20:27:35] [Server thread/INFO]: vvghfhgf[local:E:56811e42] logged in with entity id 29 at (-7.376392671812647, 118.0, 104.81557579541872) [20:27:35] [Server thread/INFO]: vvghfhgf joined the game [20:27:35] [Render thread/INFO]: Loaded 500 advancements [20:27:35] [Worker-Main-9/INFO]: [STDOUT]: [SKlauncher/ERROR] Failed to get skin for aa99cdd4-ec8b-3aa0-9a0d-1ad865da2a43: java.io.IOException: Response code: 204 	at com.sklauncher.injector.Utils.readStringFromURL(Utils.java:56) 	at com.sklauncher.injector.Utils.readStringFromURL(Utils.java:37) 	at com.sklauncher.injector.MojangSkinProvider.getSkin(MojangSkinProvider.java:17) 	at com.sklauncher.injector.transformers.SkinManagerTransformer.hookProfile(SkinManagerTransformer.java:83) 	at net.minecraft.class_1071$1.method_54647(class_1071.java:51) 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)  [20:27:38] [Server thread/INFO]: Saving and pausing game... [20:27:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:overworld [20:27:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_nether [20:27:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_end [20:27:55] [Server thread/INFO]: Saving and pausing game... [20:27:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:overworld [20:27:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_nether [20:27:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_end [20:27:59] [Render thread/WARN]: Warning! Mod mixinextras has a broken icon, loading default icon [20:28:00] [Render thread/WARN]: Warning! Mod com_electronwill_night-config_toml has a broken icon, loading default icon [20:34:30] [Render thread/INFO]: Checking mod updates... [20:34:31] [Worker-Main-6/INFO]: Update available for 'fabric-api@0.100.4+1.21', (-> 0.100.6+1.21) [20:35:22] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, configured, easymagic, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, modmenu [20:35:22] [Worker-Main-14/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading [20:35:22] [Worker-Main-12/INFO]: Found unifont_jp_patch-15.1.05.hex, loading [20:35:23] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play [20:35:23] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break [20:35:23] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Hoparlör (Realtek(R) Audio) [20:35:23] [Render thread/INFO]: Sound engine started [20:35:23] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas [20:35:23] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas [20:35:23] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas [20:35:23] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas [20:35:23] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas [20:35:23] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas [20:35:23] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas [20:35:23] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas [20:35:23] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas [20:35:23] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas [20:35:23] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas [20:35:23] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas [20:35:23] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas [20:35:23] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas [20:35:23] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program. [20:35:47] [Server thread/INFO]: Saving and pausing game... [20:35:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:overworld [20:35:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_nether [20:35:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_end [20:35:57] [Server thread/INFO]: vvghfhgf lost connection: Disconnected [20:35:57] [Server thread/INFO]: vvghfhgf left the game [20:35:57] [Server thread/INFO]: Stopping singleplayer server as player logged out [20:35:57] [Server thread/INFO]: Stopping server [20:35:57] [Server thread/INFO]: Saving players [20:35:57] [Server thread/INFO]: Saving worlds [20:35:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:overworld [20:35:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_nether [20:35:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New]'/minecraft:the_end [20:35:57] [Server thread/INFO]: ThreadedAnvilChunkStorage (New): All chunks are saved [20:35:57] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved [20:35:57] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved [20:35:57] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved [20:35:57] [Server thread/INFO]: Unloading server config for easymagic [20:35:58] [pool-5-thread-1/INFO]: Reloading server config for easymagic [20:35:58] [Render thread/INFO]: Stopping!

**Comment by Fuzss** [comment]
Possible now by updating both Puzzles Lib and Forge Config Api Port to the latest version.
